version: "3.8"
services:
  saml-proxy-envoy:
    image: envoyproxy/envoy-alpine:v1.19-latest
    container_name: saml-proxy-envoy
    volumes:
      - ./envoy:/etc/envoy
      - ./ssl:/ssl
    networks:
      - envoy-net
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8443
  saml-proxy-dev:
    image: ncreativesystem/golang-developments:dev
    tty: true
    container_name: saml-proxy-dev
    volumes:
      - .:/src/:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    environment:
      TZ: Asia/Tokyo
    networks:
      - envoy-net
networks:
  default:
    name: bridge
  envoy-net:
    name: envoy-net
    driver: bridge
